spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ddd_admin?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
jwt:
  secret: Y2FzdGxlZmVzdHdlYmNyYWRpbmdyZWV0b21pY2hhZWxkb3VzdGhpc3NlY3JldGtleW11c3RiZXF1aXRlbG9uZ2VybmdhbmR2ZXJ5c2VjdXJl
  expiration-ms: 3600000

springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true
    operations-sorter: alpha
    deep-linking: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: true